service: mailing-list

provider:
  name: azure
  location: Australia East

plugins:
  - serverless-azure-functions

functions:
  signup:
    handler: handler.signup
    events:
      - http: true
        x-azure-settings:
          methods:
            - POST
          authLevel: anonymous

  sendWelcomeEmail:
    handler: handler.sendWelcomeEmail
    events:
      - queue: mailing-list-signup-received
        x-azure-settings:
          name: item
          connection: AzureWebJobsStorage
