service: mailing-list

provider:
  name: azure
  location: Australia East

plugins:
  - serverless-azure-functions

package:
  exclude:
    - tmp/**
    - .git/**
    - node_modules/**

functions:
  signup:
    handler: handler.signup
    events:
      - http: true
        x-azure-settings:
          methods:
            - POST
          authLevel: anonymous

  email:
    handler: handler.email
    events:
      - queue: mailing-list-signup-received
        x-azure-settings:
          name: item
          connection: AzureWebJobsStorage
