service: mailing-list

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2

functions:
  signup:
    handler: handler.signup
    events:
      - http:
          path: signup
          method: post
  sendWelcomeEmail:
    handler: handler.sendWelcomeEmail
    events:
      - sns: mailing-list-signup-received
