service: mailing-list

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2

functions:
  signup:
    handler: handler.signup
    events:
      - http:
          path: signup
          method: post
    role: signupRole

  sendWelcomeEmail:
    handler: handler.sendWelcomeEmail
    events:
      - sns: mailing-list-signup-received
    environment:
      SENDGRID_API_KEY: ${env:SENDGRID_API_KEY}

resources:
  Resources:
    signupRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: SignupRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: myPolicyName
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: arn:aws:logs:ap-southeast-2:997909391502:log-group:/aws/lambda/*:*:*
                - Effect: Allow
                  Action:
                    - sns:Publish
                  Resource: "arn:aws:sns:ap-southeast-2:997909391502:mailing-list-signup-received"
